export const names_suggestions = [
  "SU One",
  "SU Two",
  "SU Three",
  "SU Four",
  "SU Five",
  "SU Six",
  "SU Seven",
  "SU Eight",
  "SU Nine",
  "SU Ten",
  "SU Eleven",
  "SU Twelve",
  "SU Thirteen",
  "SU Fourteen",
  "SU Fifteen",
  "SU Sixteen",
  "SU Seventeen",
  "SU Eighteen",
  "SU Nineteen",
  "SU Twenty",
];
