import type { Network, Section, SampleUnit } from "../types";

export const dummyNetworks: Network[] = [
  {
    id: "n1",
    name: "Highway 101",
    description: "Major coastal highway with heavy traffic",
    coordinates: [37.7749, -122.4194],
    totalSections: 5,
    createdAt: "2024-01-15",
  },
  {
    id: "n2",
    name: "Downtown Ring Road",
    description: "Inner city ring road, frequent potholes",
    coordinates: [37.7833, -122.4167],
    totalSections: 3,
    createdAt: "2024-02-20",
  },
  {
    id: "n3",
    name: "Industrial Access Road",
    description: "Connects to factory zone, heavy trucks",
    coordinates: [37.7937, -122.3965],
    totalSections: 4,
    createdAt: "2024-03-10",
  },
];

export const dummySections: Section[] = [
  {
    id: "s1",
    networkId: "n1",
    name: "Section A - Mile 0-2",
    description: "Near ocean cliffs",
    coordinates: [37.7749, -122.4194],
    chainageStart: 0,
    chainageEnd: 2,
    width: 12,
    length: 2,
    pixelToMmFactor: 0.5,
    area: 24000, // sqm
    sampleUnitCount: 4,
    createdAt: "2024-01-20",
  },
  {
    id: "s2",
    networkId: "n1",
    name: "Section B - Mile 2-5",
    description: "Urban overpass",
    coordinates: [37.777, -122.418],
    chainageStart: 2,
    chainageEnd: 5,
    width: 10,
    length: 3,
    pixelToMmFactor: 0.6,
    area: 30000,
    sampleUnitCount: 3,
    createdAt: "2024-01-25",
  },
  {
    id: "s3",
    networkId: "n2",
    name: "Ring Road North",
    description: "North segment, residential",
    coordinates: [37.7833, -122.4167],
    chainageStart: 0,
    chainageEnd: 1.5,
    width: 8,
    length: 1.5,
    pixelToMmFactor: 0.4,
    area: 12000,
    sampleUnitCount: 2,
    createdAt: "2024-02-25",
  },
  {
    id: "s4",
    networkId: "n2",
    name: "Ring Road East",
    description: "East segment, commercial",
    coordinates: [37.785, -122.414],
    chainageStart: 1.5,
    chainageEnd: 3.2,
    width: 9,
    length: 1.7,
    pixelToMmFactor: 0.45,
    area: 15300,
    sampleUnitCount: 3,
    createdAt: "2024-03-01",
  },
  {
    id: "s5",
    networkId: "n3",
    name: "Factory Entrance",
    description: "Heavy truck traffic",
    coordinates: [37.7937, -122.3965],
    chainageStart: 0,
    chainageEnd: 1.2,
    width: 15,
    length: 1.2,
    pixelToMmFactor: 0.7,
    area: 18000,
    sampleUnitCount: 2,
    createdAt: "2024-03-15",
  },
];

export const dummySampleUnits: SampleUnit[] = [
  {
    id: "su1",
    sectionId: "s1",
    name: "SU-01",
    imageUrl: "https://picsum.photos/seed/1/800/600",
    predictedImageUrl: "https://picsum.photos/seed/1/800/600?grayscale",
    pixelToMmFactor: 0.5,
    distressType: "Pothole",
    severity: "H",
    potholeDepth: 15,
    note: "Deep pothole near curb",
    detectedDistresses: [
      {
        type: "Pothole",
        severity: "H",
        averageWidth: 0.8,
        length: 0.9,
        area: 0.72,
        perimeter: 3.4,
        confidence: 0.92,
      },
      {
        type: "Longitudinal Crack",
        severity: "M",
        averageWidth: 0.05,
        length: 2.1,
        area: 0.105,
        perimeter: 4.3,
        confidence: 0.78,
      },
    ],
    createdAt: "2024-01-22",
  },
  {
    id: "su2",
    sectionId: "s1",
    name: "SU-02",
    imageUrl: "https://picsum.photos/seed/2/800/600",
    predictedImageUrl: "https://picsum.photos/seed/2/800/600?grayscale",
    pixelToMmFactor: 0.55,
    distressType: "Alligator Crack",
    severity: "M",
    potholeDepth: undefined,
    note: "Network of fine cracks",
    detectedDistresses: [
      {
        type: "Alligator Crack",
        severity: "M",
        averageWidth: 0.03,
        length: 0,
        area: 0.45,
        perimeter: 6.7,
        confidence: 0.85,
      },
    ],
    createdAt: "2024-01-23",
  },
  {
    id: "su3",
    sectionId: "s2",
    name: "SU-03",
    imageUrl: "https://picsum.photos/seed/3/800/600",
    predictedImageUrl: "https://picsum.photos/seed/3/800/600?grayscale",
    pixelToMmFactor: 0.6,
    distressType: "Transverse Crack",
    severity: "L",
    potholeDepth: undefined,
    note: "Across entire lane",
    detectedDistresses: [
      {
        type: "Transverse Crack",
        severity: "L",
        averageWidth: 0.02,
        length: 3.5,
        area: 0.07,
        perimeter: 7.0,
        confidence: 0.88,
      },
    ],
    createdAt: "2024-01-26",
  },
  {
    id: "su4",
    sectionId: "s3",
    name: "SU-04",
    imageUrl: "https://picsum.photos/seed/4/800/600",
    predictedImageUrl: "https://picsum.photos/seed/4/800/600?grayscale",
    pixelToMmFactor: 0.4,
    distressType: "Pothole",
    severity: "M",
    potholeDepth: 8,
    note: "Medium depth",
    detectedDistresses: [
      {
        type: "Pothole",
        severity: "M",
        averageWidth: 0.6,
        length: 0.7,
        area: 0.42,
        perimeter: 2.6,
        confidence: 0.94,
      },
    ],
    createdAt: "2024-02-26",
  },
];

// Historical PCI data per section (for trend)
export const historicalPCI: Record<string, { date: string; pci: number }[]> = {
  s1: [
    { date: "2024-01-20", pci: 78 },
    { date: "2024-02-20", pci: 72 },
    { date: "2024-03-20", pci: 65 },
    { date: "2024-04-20", pci: 58 },
  ],
  s2: [
    { date: "2024-01-25", pci: 85 },
    { date: "2024-02-25", pci: 82 },
    { date: "2024-03-25", pci: 79 },
  ],
  // add more as needed
};

// Unit costs for maintenance actions (per m² or per meter)
export const unitCosts = {
  "Crack Sealing": { unit: "meter", cost: 5 },
  "Pothole Patching": { unit: "sqm", cost: 30 },
  "Thin Overlay": { unit: "sqm", cost: 45 },
  "Full Reconstruction": { unit: "sqm", cost: 120 },
  "Rutting Repair": { unit: "sqm", cost: 50 },
};

// Maintenance rules: based on PCI and distress types
export const maintenanceRules = [
  { minPci: 0, maxPci: 40, action: "Full Reconstruction", priority: "High" },
  { minPci: 41, maxPci: 55, action: "Thin Overlay", priority: "High" },
  {
    minPci: 56,
    maxPci: 70,
    action: "Pothole Patching / Crack Sealing",
    priority: "Medium",
  },
  {
    minPci: 71,
    maxPci: 85,
    action: "Preventive Maintenance (Crack Sealing)",
    priority: "Low",
  },
  { minPci: 86, maxPci: 100, action: "Routine Maintenance", priority: "Low" },
];
